### PR TITLE
added ratelimitimng to the genAI route as asked

### PR DESCRIPTION
**Pull request by Abhinandan-4321**
have made the necessary changes as asked

### CODE REVIEW

**Comment by Abhinandan-4321** [comment]
You can review this PR #45

**Comment by Swasti008** [comment]
@CodiumAI-Agent /review

**Comment by Abhinandan-4321** [comment]
I there any change you would like me to do?

**Comment by Swasti008** [comment]
@Abhinandan-4321 , No changes required as per AI-review.

**Comment by Abhinandan-4321** [comment]
Okay. You can merge this PR now.

**Comment by Swasti008** [comment]
Thanks for contribution @Abhinandan-4321 .
Merging this to main branch and closing the issue #44.

**Pull request merged**
