### PR TITLE
Typewriter animation

### PR DESCRIPTION
**Pull request by ananyatewari**
I have made the PR as requested in #39 

I would request you to review it

### CODE REVIEW

**Comment by Swasti008** [comment]
@CodiumAI-Agent /review

**Comment by Swasti008** [comment]
@CodiumAI-Agent /review

**Comment by Swasti008** [comment]
Can you please make changes on the issue Potential XSS Vulnerability and Code Quality Improvement Needed in Typewriter Component , as suggested by AI-review?

**Comment by Swasti008** [comment]
@ananyatewari Can you please share the screenshot of final required output ?

**Comment by ananyatewari** [comment]
WhatsApp Image 2024-06-26 at 16 56 07_1a9f4825

**Comment by Swasti008** [comment]
Thanks for contribution.

Merging with main brack nad marking #39 as closed.

**Comment by Swasti008** [comment]
Thanks for contribution.

Merging with main branch and marking https://github.com/kalviumcommunity/S59_Swasti_Capstone_OrbitIQ/issues/39 as closed.

**Pull request merged**
